---
title: "Toilet Data"
author: "Nicole LaPointe Jameson"
date: "February 6, 2016"
output: html_document

---
#Importation and Cleaning of Public Restroom Data

##Establishing the Workbench
```{r, message=FALSE}
library(ggmap)
```

##Data Importation
```{r, message=FALSE}
NYCToilets <- read.csv("/Users/NMLJ/Desktop/GitHub/project2-group10/data/NYCToilets.csv", header=TRUE)
NYCToilets <- as.data.frame(NYCToilets)
```

##Geocoding Latitude and Longitude
```{r, results="hide"}
LLnew <- as.matrix(geocode(as.character(NYCToilets$Location[1:608]), output = c("latlon"),source = c("google", "dsk")))

NYCToilets$Lat <- LLnew[1:608,2]
NYCToilets$Lon <- LLnew[1:608,1]
```

##Recoding the Variables
```{r}
NYCToilets$Name <- as.character(NYCToilets$Name)
NYCToilets$Location <- as.character(NYCToilets$Location)
NYCToilets$YearRound <- as.factor(NYCToilets$YearRound)
NYCToilets$Handicap <- as.factor(NYCToilets$Handicap)
NYCToilets$Borough <- as.factor(NYCToilets$Borough)
levels(NYCToilets$Borough)

summary(NYCToilets)

#NA Removal: Final Data Set
NYCT <- na.exclude(NYCToilets) 
summary(NYCT)
```

##Write New Data Set
```{r, message=FALSE}
write.csv(NYCT,file = "/Users/NMLJ/Desktop/GitHub/project2-group10/data/NYCT.csv")
```
